## Numpy: 
Numpy stands for Numerical Python and is the backbone for calculations in python for many libraries. This is due to being able to have more control over calculations and the memory storage for numbers and enabling array manipilation and computations with arrays and matrixes.  
Numpy is built on the backbone of C to be able to utilize the faster computation speed and having control over the memory used for numbers to achieve the above. 

In [1]:
import sys
import numpy as np

In [2]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([0, .5, 1, 1.5, 2])
# numpy arrays will act like a python list but will have better performance and memory usage due to being driven by C primitive data types and not python objects

In [3]:
array_a.dtype
# numpy automatically created the first array using int32

dtype('int32')

In [4]:
np.array([1, 2, 3, 4], dtype=np.int8)
# However you can specify the data type as needed.

array([1, 2, 3, 4], dtype=int8)

## Multidimensional Arrays

In [5]:
two_dim_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
two_dim_array.shape
# note the comma seperating the 2 one dimensional arrays that this numpy is created from.

(2, 3)

In [6]:
three_dim_array = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
# note that for a 3 dim array that you need to have the different "layers" be the same shape for it to function as a numpy array

three_dim_array.shape

(2, 2, 3)

### Statistics on Arrays or Matrices

In [7]:
a = np.array([1, 2, 3, 4])
a.mean()

2.5

In [11]:
matrix_stat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix_stat.mean()
# can use the axis parameter to specify if you want the mean for rows or columns. can be used for other statistics too. examples below

5.0

In [9]:
matrix_stat.sum(axis=0)
# adds up all the columns

array([12, 15, 18])

In [10]:
matrix_stat.sum(axis=1)
# adds up all the rows

array([ 6, 15, 24])

In [14]:
matrix_stat.mean(axis=0)
# mean for the columns

array([4., 5., 6.])

In [15]:
matrix_stat.std(axis=1)
# standard deviation for the rows

array([0.81649658, 0.81649658, 0.81649658])

### Vectorized Operations and Boolean arrays  
These are a strong ability that numpy brings to the table.

In [23]:
array_a = np.arange(4)
array_a+10

array([10, 11, 12, 13])

In [19]:
array_a*10

array([ 0, 10, 20, 30])

In [20]:
array_b = np.array([10, 11, 12, 13])

In [21]:
array_a+array_b
# can easily do math on arrays of the same shape

array([10, 12, 14, 16])

In [27]:
array_a[[False, False, True, True]]
# typing it out like this is very tedious when you have a large array or matrix, however you can do this with boolean operations.

array([2, 3])

In [26]:
array_a >= 2

array([False, False,  True,  True])