## Numpy: 
Numpy stands for Numerical Python and is the backbone for calculations in python for many libraries. This is due to being able to have more control over calculations and the memory storage for numbers and enabling array manipilation and computations with arrays and matrixes.  
Numpy is built on the backbone of C to be able to utilize the faster computation speed and having control over the memory used for numbers to achieve the above. 

In [1]:
import sys
import numpy as np

In [2]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([0, .5, 1, 1.5, 2])
# numpy arrays will act like a python list but will have better performance and memory usage due to being driven by C primitive data types and not python objects

In [3]:
array_a.dtype
# numpy automatically created the first array using int32

dtype('int32')

In [4]:
np.array([1, 2, 3, 4], dtype=np.int8)
# However you can specify the data type as needed.

array([1, 2, 3, 4], dtype=int8)

## Multidimensional Arrays

In [5]:
two_dim_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
two_dim_array.shape
# note the comma seperating the 2 one dimensional arrays that this numpy is created from.

(2, 3)

In [6]:
three_dim_array = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
# note that for a 3 dim array that you need to have the different "layers" be the same shape for it to function as a numpy array

three_dim_array.shape

(2, 2, 3)

### Statistics on Arrays or Matrices

In [7]:
a = np.array([1, 2, 3, 4])
a.mean()

2.5

In [11]:
matrix_stat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix_stat.mean()
# can use the axis parameter to specify if you want the mean for rows or columns. can be used for other statistics too. examples below

5.0

In [9]:
matrix_stat.sum(axis=0)
# adds up all the columns

array([12, 15, 18])

In [10]:
matrix_stat.sum(axis=1)
# adds up all the rows

array([ 6, 15, 24])

In [14]:
matrix_stat.mean(axis=0)
# mean for the columns

array([4., 5., 6.])

In [15]:
matrix_stat.std(axis=1)
# standard deviation for the rows

array([0.81649658, 0.81649658, 0.81649658])

### Vectorized Operations, Boolean arrays, Linear Algebra Calculations  
These are a strong ability that numpy brings to the table.  
Numpy is very good for python as it lowers the memory size for different number types, and brings great performance for calculations.

In [23]:
array_a = np.arange(4)
array_a+10

array([10, 11, 12, 13])

In [19]:
array_a*10

array([ 0, 10, 20, 30])

In [20]:
array_b = np.array([10, 11, 12, 13])

In [21]:
array_a+array_b
# can easily do math on arrays of the same shape

array([10, 12, 14, 16])

In [27]:
array_a[[False, False, True, True]]
# typing it out like this is very tedious when you have a large array or matrix, however you can do this with boolean operations.

array([2, 3])

In [26]:
array_a >= 2

array([False, False,  True,  True])

In [41]:
array_a[array_a >= 2]

array([2, 3])

In [43]:
array_a[array_a >= array_a.mean()]

array([2, 3])

In [46]:
random_matrix = np.random.randint(100, size = (4, 4))
random_matrix

array([[19, 45, 71, 47],
       [75, 79, 15, 54],
       [78, 19, 62, 16],
       [ 9, 66, 54, 97]])

In [47]:
random_matrix[random_matrix > 30]

array([45, 71, 47, 75, 79, 54, 78, 62, 66, 54, 97])

In [48]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [49]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [50]:
A.dot(B)
# dot procuct for matrixes

array([[20, 14],
       [56, 41],
       [92, 68]])

In [51]:
A @ B
# matrix multiplication symbold is @

array([[20, 14],
       [56, 41],
       [92, 68]])

In [52]:
B.T
# transposing matrix

array([[6, 4, 2],
       [5, 3, 1]])

#### Important Functions: 
- random
    - generates random numbers 
- aramge
    - creates array from the range of numbers specified
- reshape
    - reshapes an array with the specified shape
- linspace
    - creates an array with the numbers between 2 end points with an even interval
- identity
    - square array with 1's down the diagonal, useful for linear algebra
- eye
    - 2D array with 1's down the main diagonal, can move where the diagonal starts



In [58]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(5, 10)


array([5, 6, 7, 8, 9])

In [60]:
np.arange(0, 1, .1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [61]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [63]:
np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [64]:
np.linspace(0, 1, 20, False)


array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [72]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(8, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.eye(8, 4, k=1)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.eye(8, 4, k=-3)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])